### ISSUE TITLE
Mosfet 

### ISSUE THREAD

**Issue by TillyMasters1** [Frostist/RGB-LED-Strip-ESP8266-Homekit#1]
What Mosfet do i need for my 5v light strip? and im powering it from the vin pin on the 8266

**Comment by Frostist** [comment]
Hmmm, this was the light strip I bought: https://www.takealot.com/multipurpose-5m-smd-5050-60led-rgb-strip-light/PLID70902466

I used the power supply from the LED strip to power the strip and then used a micro-usb power supply to power the ESP board.

**Comment by Frostist** [comment]
Done
